# Indexes from one
set -g base-index 1
setw -g pane-base-index 1

# Disable background for status bar
set -g status-style "bg=default fg=default"

# Disable status-right
set -g status-right ""

# Pi agent wants extended keys enabled
set -g extended-keys on
# Pi agent doesn't like xterm
set -g extended-keys-format csi-u
